### ISSUE TITLE
An ACL paper for using GCN in coreference resolution

### ISSUE THREAD

**Issue by ianycxu** [IndexFziQ/GNN4NLP-Papers#3]
Hi,

Could you help add this paper to the list: https://www.aclweb.org/anthology/W19-3814/

Thanks,
Ian

**Comment by IndexFziQ** [comment]
Hello, lan:
Thank you for your suggestion! And you can fork my repository, edit your
suggestions and I will merge your job!
And I will give the tutorial for contributors.
Regards, Xie

ianycxu ***@***.***> 于2021年5月18日周二 上午10:02写道：

**Comment by IndexFziQ** [comment]
Hello, lan:
Thank you for your suggestion! And you can fork my repository, edit your suggestions and I will merge your job!
And I will give the tutorial for contributors.
Regards, Xie
